travis:
  secure:
    BINSTAR_TOKEN: MlsEEg4qk7KSTiuHpNUGvPpXh+KZCTACoWJvI8WZNg8srKOXTAgP886XN/vDdVHteJ9ps4Xnx6gCztxfauTZtBGcTlZsTysmMpd8PMwL2RyWDgpC3th0goU0zjy3XlDiOkt/5dhNGbapxgExqbZGby1KFs2h4d6zqWCN2bqTtSQLagsQVBGLY2AQ+o4D8cEFXc4F7AO0HGH/G2kvxtSp+3lZ+ZVECERQgz4DEfAiW4ViGaGJXRYiaH72zv2hSk8xPAsnhFvGlJtcNMKXS1Md+KSDfN3P60vJKSGGyM9anue1cp5WWi/C5JBUy47Bv1QKTFxH+1VJU/Y7RIYNYPVjgXsDHYNJhfSx4CnS1hfQ+Nuu3TnEUx0IRrr1fJ3HkK+QfxoRPRjX24xgMT1+kRyD2h5WtbQ6nsXcGBmrIxE/mVw93T1zxe3zoO91Npq/udJ0nt0pH7XMxPtVXisprkWsF01Xrf63pC+vq+L6OEYvA9MTA/DMu6PZz3wzm2NTZ0Icu5MwpmlBbGZX8k2PptaudijaoA1XEKG04uoyz5O7mRJpIN7FAy3MRXPzxYuNWPnF4JT+43bXkJg17MYdxOPyySHh5lW3PkYSn3AP7oXOr56Q8ogk73JfCit4CIaHnklmbRlJeHLETPx3lb2HbBfHYCfyduKpof3cgw3pqCmbups=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
