travis:
  secure:
    BINSTAR_TOKEN: q06hNgkL5iLpMgKX/n2oExbtwmZQXSjJygBmOKzf/oTARQxEBPlOyiqQyHOvssEtETnUnyjwJZJS3vJw9rNPwHZD5GBDoOsLjbiRAvVJVapRtlMThb/IfOtOsAY6SacLHDNVwtOtE12Slv4PjeDTO8uerphH3pSdg/FrZTGxJZtsf21775sQm4WMh9tTIBQuULQWz2BPJDPPtOpnwDXZEVushGoLdFoj6QyxDmITE3L4GAVtYN8055FBuTWxqjnKfgOpjolmhFj6RAyeoNCirrJ/LGwoazaiD/tLIlPWXyuD8pvxp7yYF6IJSJOnDSYscdYbYzWuiwvGpnRSnVF8xLIioMBfwC10ey6dWLtWcKYcQhIhHjBEZD58elz1q8FBVWfD49ptBPWIUkk3CZUbAVtddgO+YDcZDWRvwLRqzQwsFDkAT61mMLDpuPHDM7ikzz/7lhVaTRYRM46ac9uL/+2dD+jxS4ov2o18gAVYl7+ED/nFCqVn8zDpVfvSnKptDE4JI4x7BdPiOIQVNna1XEVYrQ0oDZB9M0ix1hXNXK0+6OOP8C6gwCn3rWh9Sfj+legf3zybHbEJ69aYQg1X6sbpryd2OGC98+2md8IukziOkiEoMdxYvx9nc5k33i9EDqrZXlp3+USza7P4sQYi0DfCatt80B0PD1+ubWWvP48=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
