travis:
  secure:
    BINSTAR_TOKEN: GAFSN29LEk8DzVBOZ57wCBjkiUyhEUwstx5BLYOgQcVUcg4TOQZZvjXvLgHoPCO/OZGFRQF0SxmP+PWv1pd3NrAYw0kR75t9rGQNt5zyL580rBUpjP5HvQmxxrWsYjmxDPecWsDjNNggSaQoU8whj8E5Rj6QhZnLu6+Y9/gDzD+1mxDXXgSDuUiiYCxKPYLfx39/OPr7ryZEG5eRY3Obw95eaxta8pc0FhyhDHnAR86DOtBGRgpAE4Vzzv68arwef2zObOtE6m/42+qtcESkDzA9sWNE9+t59xac9jmMNMKMUvnlMzXtmEwUoxXKCmAQjMq8paIgDrR/OgssQPxJQ/QwItOaO+OEVdZi5T5Uhb6Db36hReqGymsWll0fCwHHEzbJ2oaQjh7hichNEK2MoXDyvWOGvAfW2RSb00EaUYHJCijS7s1uR/11Oww6bmA2+jxIPTL19gb8b9g4J5hdEmp+t/XYtUo0mkzPM0xCs24cUVFLkTl8IfWzFu3VQV5jnYQCyTxrphNHnKvTEFglHDyCUPIu90cHnqdK02pK6gCcpzqPe+4hG7lKKzkjIlg0JfhBgtSMGC8N839Qo4dpBFXS2pahpzmNoNiBdbZvMRtbEE5JSlENqTekxMhsoOPg7nrK+b5En/5F4GcidGL2j/uST9HQHgSHqXG3h4SKOe8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
