travis:
  secure:
    BINSTAR_TOKEN: B87/g4lNGd8GFpS0AZK15T+yH34swUtNM1Jr71Qw3CryQgViqvQpwzJX76h3Iamj9lChEBpj0MDNfuuiHx3Dfq4n9OBznNJxS3k/iZqDHC90aXJr6P0x5f3l6xcYnKTHSXA0x7KiVWK+b77a+LknbFZPmdV8zDMUU4oR9+R1EuB93cKxHAOXKeAT61NAGlWgpSHAqXvXIVfXxRyu9OzsecrHDR0zkDDiLl0FX6+ZeVc3wPHCM6qXOFPw58dceeyzNpFfnIBQ3YwEx/qZCkLRLy46PDsEZOB8N/xJTGAKOKHEVDXhjm8W9LbYOo0TK8Bh9keB71F/IrGxJG4Z/v7ydE5hdCnfiEXSwdFFzWIBBYH3Sq031S55ZOdgi1tBUuw5Jpor4gH0ibeLKShZRG5cCwLnOSGQf810m4ixit7ra2oTZ9TOsHwa6u7joL3aO7qdvgehwqAJEAw1gMWm8QQC4HCgfFba3DKG+iqqnj31wYdIcEdzlemgBDM7BxpEVuyFZgdAj0I3HZRkAMWPVetFM5mL96OAhNJL6T17EIf/rXe0tWUEQGCnsOkIlUCiWlSkb2/l2rNXiGIBXcuk6FdynG4Vua7B4PBVy2Eij3He4Jorwy07GZuQB0/Vp4NU8fOjznG2Y+mcalsQtRJzlfRxr7YujpyMQ+gh4q00PtSZP9k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
